### ISSUE TITLE
This app can't run on your PC - Windows 10

### ISSUE THREAD

**Issue by sanyogthescholar** [Toinane/colorpicker#107]
**Describe the bug**
I installed the app using the exe from the releases tab, but I am unable to open the application. This app can't run on your PC window is displayed

**To Reproduce**
1. Download colorpicker_setup_2.0.3.exe from releases
2. Install it
3. After installation try to open it. Above issue occurs

**Expected behavior**
The application should launch

**Screenshots**
![image](https://user-images.githubusercontent.com/50242941/127439116-f2cfa595-31fc-432b-9c17-6a971d73529f.png)

**OS:**
 - OS: Windows 10
 - Version: 20H2

**Colorpicker:**
 - Version 2.0.3

**Comment by Toinane** [comment]
Hey @sanyogthescholar i'm sorry you have this issue..
It a bit strange, I don't have any issue on my side with my Windows 10 21H2.
Can you try to download it and reinstall it? And if it don't work again, can you give me the specifications of your computer?
Thank you!
