### ISSUE TITLE
Colorpicker window doesn't display after started

### ISSUE THREAD

**Issue by lego37yoon** [Toinane/colorpicker#114]
**Describe the bug**
Colorpicker window doesn't display after started. It has a preview, but when try to display, it suddenly displayed on the top-right corner of the window, and after 0.1 second, automatically minimized.

**To Reproduce**
1. Install Colorpicker 2.0.3 on your Windows device.
2. Click 'Colorpicker' at the Start menu.
2. Try to click 'Colorpicker' icon at the task bar.
3. Doesn't display

**Expected behavior**
Displayed on window.

**Screenshots**
![image](https://user-images.githubusercontent.com/7126454/139777467-3d998e9d-8d45-4541-b135-656260672078.png)
*Preview Image*
![image](https://user-images.githubusercontent.com/7126454/139777650-843c84af-1817-4424-be34-34d0dda8ce11.png)
*When move mouse cursor to the preview, nothing showing except background*

**OS (please complete the following information):**
 - OS: Windows 11 Pro Insider Preview
 - Version : Build 22483.rs_prelease.211015-1431
 - Same problem occured since Build 22471

**Colorpicker (please complete the following information):**
 - Version 2.0.3

**Additional context**
- This bug happened after I connected additional monitor via Type-C DP Alt mode and HDMI.
- After disconnect my monitor or re-connect my monitor: same problem occured.
- Other Electron-based apps like *Notion*, *Typora*, *Visual Studio Code* are working correctly.
- Tested on my 15-inch laptop; Here is specifications below:
  - Model: LG gram 15ZD90N-HX56K
  - CPU: 10th-gen Ice Lake Intel(R) Core i5-1035G7
  - GPU: Integrated Graphics - Intel Iris Graphics G7
  - RAM: 8GB DDR4 3200Mhz * 2
  - Storage: 256GB TLC SSD (OS), 1TB QLC SSD (Model: Crucial P1)
  - Fingerprint Sensor enabled
  - Network: Intel AX201 WiFi 6, Bluetooth 5
  - Display: 1920 * 1080 / Touch Enabled / 15-inch display
- Attached monitors:
  - 15-inch display / 1920 * 1080 / Touch Enabled / connected via Type-C DP Alt mode
  - 24-inch display / 1920 * 1080 / Touch Unavailable / connected via HDMI

**Comment by Layoutlab** [comment]
Great tool, I keep coming back hoping the problem is solved! The same issue here. I tried versions. Still the same. Normally if the apps is out of the boundary, shift+right click to move back to the window  is the option. This too is missing on the preview on the taskbar.

**Comment by Toinane** [comment]
Hey @Layoutlab @lego37yoon i'm sorry you experiencing this issue! I'm a bit off actually but I'll fix this bug for the next update when possible 👍

**Comment by Toinane** [comment]
Hey @Layoutlab @lego37yoon can you try it again with the new update? It should be good now

**Comment by lego37yoon** [comment]
Hello, I had some problem that I couldn't use my laptop these days, but today I got my laptop back, so I tested Colorpicker 2.1.0.

![image](https://user-images.githubusercontent.com/7126454/171647952-1b6bfdba-de76-4d5c-9ffb-11395d238839.png)
It seems working well in **Windows 11 Pro Insider Preview Build 25115.rs_prerelease.220506-1410**.
Thank you for making great application!

**Comment by Toinane** [comment]
great news! Thank you and sorry for the late response/fix 👍

**Comment by Salman-Sali** [comment]
I have the same issue with the latest release 2.2.0 on windows. My OS is Windows 10. 
The issue is virtually the same on my system. I install and open the color picker and it stays minimized with no way to maximize it. If I click repeatedly multiple times, I can see the window pop open for a fraction of a second.
