### ISSUE TITLE
Question regarding next update 3.0

### ISSUE THREAD

**Issue by IshanJ25** [Toinane/colorpicker#116]
When will it be released? Any estimate?

**Comment by Toinane** [comment]
Hey @IshanJ25 sorry for this long moment without any news. I haven't any times before for Colorpicker..
Until now! I'm currently in reflexion about the new design UI of Colorpicker. In the same time I'm trying to make the new C++ picker/eyedropper (I've a working test on Windows only)

So I can't really estimate when the next update will coming. But I can say it will be really good one 😄 a lot of news features is coming

**Comment by IshanJ25** [comment]
okay
I filled that survey btw
nice application

**Comment by Toinane** [comment]
Here is a first possible preview for the interface

**Comment by Toinane** [comment]
> okay
> I filled that survey btw
> nice application

Thank you! I read any news comment from the survey, it's really helpful 👍

**Comment by IshanJ25** [comment]
> > okay
> > I filled that survey btw
> > nice application
> 
> Thank you! I read any new comment from the survey, it's really helpful 👍

You're welcome

> Here is a first possible preview for the interface![61d97a017e5cd.gif](https://user-images.githubusercontent.com/7584391/150580455-e7bda76e-26cd-4700-9052-3f8d8d195f18.gif)

Looks good
