### ISSUE TITLE
Second display color picking bug

### ISSUE THREAD

**Issue by neNerower** [Toinane/colorpicker#119]
This problem only occurs when I try to **pick a color** with a **second monitor** connected to my laptop.

It means that everything works correctly **until** I try to use the **color picker function**.
After that, there are two possible cases.

**First one**
If the application window was **originally** located on the **main monitor**, then after that the picker cursor suddenly jumps to the second monitor, and then continues to repeat the mouse movement and correctly determines the color, but **only on the second monitor**, and **cannot go beyond** it (although all movements mice are produced on the main monitor).

**Second one**
If the application window was opened on the **second monitor**, then after pressing the button for picking the color, the picking cursor cuddles tightly to the far side of the second monitor, and moves with the mouse **only vertically** without breaking away from the edge of the screen. 

This continues until the mouse moves to the main display, after which the picker cursor behaves as described in the first case. 

-------

**Versions:**
 - Ubuntu 20.04 LTS
 - Colorpicker 2.0.3 (from snap store)

**Comment by Toinane** [comment]
Hey @neNerower thank you for the report, I'll see what I can do for this

**Comment by Toinane** [comment]
Should be fixed in v2.2.0 👍 
Feel free to reopen if needed
