### ISSUE TITLE
Win10 - JS Error: Uncaught Exception

### ISSUE THREAD

**Issue by bgriffith79** [Toinane/colorpicker#134]
Description:
When using Eyedropper tool, hovered over a webpage to capture RGB Hex-Code, JS threw Uncaught Exception

To Reproduce:
Not certain, I've used it many times prior (>30 at least) with no issue whatsoever (Kudos! Love the app btw!).

Expected Behavior:
Capture of the underlying RGB Hex-Code

Screenshot:
![image](https://user-images.githubusercontent.com/119703760/216461466-a4f6e9b4-7a06-4c94-956e-9688cb042042.png)

OS/Version:
Windows 10 Pro/Build 19045.2364 

Colorpicker v. 2.2.0

**Comment by Toinane** [comment]
Hey @bgriffith79 sorry that you have this issue! Looks like the config file is corrupted. I don't know why it's happen, but you can delete this file to make a new one!
The file is located to `C:\Users\[username]\AppData\Roaming\colorpicker\storage`, you can delete `colorpicker.json` file and open again Colorpicker App

**Comment by bgriffith79** [comment]
Thanks for the update. Great app!

On October 27, 2023, at 5:23 AM, Toinane ***@***.***> wrote:

Closed #134 as completed.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/Toinane/colorpicker/issues/134#event-10790002412">https://github.com/Toinane/colorpicker/issues/134#event-10790002412</a>", "url": "<a href="https://github.com/Toinane/colorpicker/issues/134#event-10790002412">https://github.com/Toinane/colorpicker/issues/134#event-10790002412</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]
