### ISSUE TITLE
update avaible message, but app already updated

### ISSUE THREAD

**Issue by 70V07** [Toinane/colorpicker#139]
**I have installed Colopicker version 2.2.0** (from About panel in app)

but every time I open settings of **app give the notification:** *New update avaible*

**Comment by FabianLoRs** [comment]
Confirmed  👍

**Comment by SudoWatson** [comment]
I am also getting this issue still. Looking into the about part in settings, it tells me there is an update available here, but the most recent version is the version that I have installed. For me it seems to give 2 update notifications whenever I open settings.

**Comment by Toinane** [comment]
Hey there, sorry for late response, I'll see what I can do for this 👍

**Comment by Toinane** [comment]
It should be resolved for now! No need to update Colorpicker app
