### ISSUE TITLE
A Java Script Error Occurred on the main process. OSX

### ISSUE THREAD

**Issue by Smoodie7** [Toinane/colorpicker#140]
**Describe the bug**
A Window error is always telling me that when I open the app

**OS (please complete the following information):**
 - OS: MacOS Venture (last version)

**Colorpicker (please complete the following information):**
 - Version: Last Version
![image](https://github.com/Toinane/colorpicker/assets/89829273/955e7d44-e41e-44b5-be5a-f5d77e2bef91)

**Comment by Toinane** [comment]
Hey @Smoodie7 sorry for the late response
The storage file is corrupted, you have to delete it manualy

To found the file colorpicker.json file, you have to go :

    Mac OS: ~/Library/Application Support/colorpicker/storage/
    Windows: C:\Users\AppData\Roaming\Colorpicker\storage
    Linux: ~/.config/colorpicker/storage

Delete it and relaunch the app, it will work again

**Comment by Toinane** [comment]
This issue will be resolved in future update. I'll close this issue for now, feel free to reopen it if needed 👍
