### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by fschlegelone** [Toinane/colorpicker#146]
Right now, the colorpicker can only run via Rosetta on macOS. 

Since most apps are already supporting arm64 based macs, your color picker is now the only app I have Rosetta installed for :D 

Thank you for maintaining this project tho, love it.

**Edit:** 
Can't run the app at all, not even via Rosetta.
![image](https://github.com/Toinane/colorpicker/assets/118682177/c4621b82-aee2-4f63-9490-da8252737a49)

**Comment by Toinane** [comment]
Hey @fschlegelone thank you for the support :) I really appreciate!
Sorry for the issue, I'll see what I can do for building arm64 macos version!

**Comment by Toinane** [comment]
I've released new release with Apple Silicon support (arm64 build)!
Feel free to open new issue if you find any issues with this version (I don't have Silicon mac, so I can't check on my side)
