### ISSUE TITLE
Erreur Javascript lors de l'ouverture dans windows 10

### ISSUE THREAD

**Issue by JacquesGiard** [Toinane/colorpicker#147]
**Describe the bug**
Lors de l'ouverture du logiciel, nous voyons apparaitre la fenêtre suivante:
![Capture](https://github.com/Toinane/colorpicker/assets/29148567/953448a7-55a6-4daf-8592-b6b830f72fcf)

**OS (please complete the following information):**
 - OS: Windows 10
 - Version 22H2

**Colorpicker (please complete the following information):**
 - Version 2.2.1

**Comment by Toinane** [comment]
Bonjour @JacquesGiard merci beaucoup pour votre retour de bug. J'ai réalisé une mise à jour qui devrait corriger ce problème !
Vous pouvez la retrouver ici https://github.com/Toinane/colorpicker/releases/tag/2.2.2
En espérant que cela résout votre problème. N'hésitez pas à revenir vers moi au besoin !
