### ISSUE TITLE
ColorBook input error

### ISSUE THREAD

**Issue by rubyframework** [Toinane/colorpicker#17]
Currently colorbook option accepts any value when trying to save a color code. If an incorrect value is entered (something other than a color code) it displays a blank space where the color circle would have gone. Some validations might be nice to have.

Great app btw!

**Comment by Toinane** [comment]
Hey! Thanks for youre message! It's planned, don't worry about it :D I work on it step by step and there is still a lot of detail missing.

**Comment by Toinane** [comment]
Here we go, it's fixed on #4b6c0e3 :)
