### ISSUE TITLE
Picker feature for Linux

### ISSUE THREAD

**Issue by Toinane** [Toinane/colorpicker#18]
Picker doesn't work on Linux. We use two native dependencies for the picker.
- On macos, we use [osx-mouse](https://github.com/kapetan/osx-mouse)
- On Windows, we use [win-mouse](https://github.com/kapetan/win-mouse)

The author of these dependencies didn't create a Linux version sadly.

So I started to fork the macos version, and try to make it compatible with Linux. As I'm not a C/C++ expert, It could be difficult.
Some help would be welcome. See [linux-mouse](https://github.com/toinane/linux-mouse)

**Comment by PostPollux** [comment]
Nice handy tool! Too bad that the picker doesn't work under linux. Unfortunately I can't help... good luck

**Comment by Toinane** [comment]
Yeah thank you! I really want to see this feature work under linux! I will search how I can make it work

**Comment by Kilian** [comment]
Maybe the implementation in http://robotjs.io/ could be of help?

**Comment by Kilian** [comment]
@Toinane Oops! I thought that could do more. sorry.

**Comment by Toinane** [comment]
Maybe I can use now iohook for this. I've created a new branch for this.

**Comment by Toinane** [comment]
Okey I've tested iohook : 
- on MacOS it work fine
- on Windows its really painfull and slow
- on Linux I haven't tested now

**Comment by Kilian** [comment]
I tried this on Ubuntu 16.04, and the picker does not seem to do anything (but there are no errors in the devtools console or in the terminal.

**Comment by Kilian** [comment]
I removed the if clause at https://github.com/Toinane/colorpicker/blob/master/src/browsers/picker.js#L11 and can confirm that it works really well on Ubuntu.

**Comment by Toinane** [comment]
Okey cool!
Thank you for your test @Kilian!
I think I will make two versions of Colorpicker to resolve this.
When I can, I test iohook on my Debian, but I suppose it will work fine like Ubuntu :)

**Comment by ctexxx** [comment]
Any updates?

**Comment by Toinane** [comment]
I've recently tested on my ElementaryOS and it worked fine! So I will make a separate version of colorpicker just for Linux with this patch when I can 👍

**Comment by rodrigorhas** [comment]
So this issue can be finally closed? Then update the project readme (wich says Linux isn't supported)

**Comment by Toinane** [comment]
Yes @rodrigorhas I'm working on the next minor release, I have already builds for Windows and Linux, I'll build the macOs version tomorrow and I publish the 2.0.3!
See #59

**Comment by Toinane** [comment]
Okay ! I've just released 2.0.3 that add picker feature for Linux ! Thanks all!
See https://github.com/Toinane/colorpicker/releases/tag/2.0.3
