### ISSUE TITLE
Please publish AppImage for Linux on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [Toinane/colorpicker#19]
Please publish an [AppImage](https://appimage.org/) for Linux on GitHub Releases.

It is already configured, so should be straightforward:

https://github.com/Toinane/colorpicker/blob/8a8f44ffdef2c11692118027c6196199bee0ae48/package.json#L12-L16

**Comment by Toinane** [comment]
Yes indeed, it's configured, I was mostly waiting for the website to finish before compiling. And above all I didn't have access to my Linux before today :)

A release will be released during the day, don't worry!

**Comment by Toinane** [comment]
There you go! It's now available here : [2.0.0](https://github.com/Toinane/colorpicker/releases/tag/2.0.0) 👍
