### ISSUE TITLE
Signed app on MacOS

### ISSUE THREAD

**Issue by KeziahMoselle** [Toinane/colorpicker#22]
I can't run colorpicker on MacOS High Sierra v10.13.3 (17D102)
It is signed ?

![Signed App](https://i.imgur.com/nHeOtwc.png)

**Comment by Toinane** [comment]
hey!
I don't have an OSX developer account, so I can't sign colorpicker.. :/
You can authorize Colorpicker anyway in your Preference's Security panel!

Sorry for this, I can't afford 99$/year just for that..

**Comment by KeziahMoselle** [comment]
Okay ! Sorry i thought it was free... But yeah Apple.
Thank's for the information i will do that :)

I understand, no problem !
Great work too

**Comment by Toinane** [comment]
Ahah no problem! I'm closing this issue right now, since I have no way to sign the app.

If I ever find a way later, I'll reopen it to correct this issue.

**Comment by jaymecd** [comment]
It's been many years @Toinane since this issue is closed, however can't use this wonderful app due to missing signature :(

**Comment by Toinane** [comment]
I know sorry, when I'll find the mood and motivation to continue the app, I'll sign it 👍
