### ISSUE TITLE
Does not support multiple monitors

### ISSUE THREAD

**Issue by bpatram** [Toinane/colorpicker#26]
When using the color picker eyedropper, if you move your cursor to a monitor different than the primary monitor the color picker always shows white (#FFFFFF) and not the actual color under the cursor.

I am using version 2.0.0

**Comment by Toinane** [comment]
Hey! It really strange, It work on my multiple monitors.. What is your OS?

**Comment by romanrandom** [comment]
Same here on macOS. I get white when **y** position is negative. It's probably related to this issue:
https://github.com/octalmage/robotjs/issues/88
which might be getting fixed here:
https://github.com/octalmage/robotjs/pull/307

**Comment by Toinane** [comment]
Oh okey, I suppose it's because I don't have negative position with my second screen on macOS, I will test that when I can I follow the fix for robotjs! Thanks @romanrandom!

**Comment by romanrandom** [comment]
You're welcome @Toinane 
I'm looking into porting my [color palette Chrome app](https://chrome.google.com/webstore/detail/color-palette-pocket/cpeodkcejoabdmfneaoihkjkibgeifci) to Electron and adding a color picker to it is my nº 1 priority

**Comment by bpatram** [comment]
@Toinane I am running macOS 10.12.6 (Sierra). I think what @romanrandom is saying regarding my displays being in a negative position may be a plausible explanation. 

However, I am unsure how I could verify this. If you could point me to the file or line of code that I could throw a breakpoint on via the developer tools and poke around to reveal the cursor position to verify that I would be more than happy to!

**Comment by bpatram** [comment]
In my particular configuration I have two monitors side by side, with my primary monitor being the right monitor and my secondary monitor on the left. However, when getting cursor position (using `xdotool`) it seems the origin is set to my left most monitor top left corner (not the primary monitor which I was expecting), so global cursor coordinates are never negative.

I have tested it using `xdotool getmouselocation` (`brew install xdotool`). I am unsure if the position reported via`xdotool` uses the same coordinate system as `robot.js` or `osx-mouse` (which is being used in this situation?)

**Comment by romanrandom** [comment]
You can check the position [here](https://github.com/Toinane/colorpicker/blob/92d788e2575efb0294e8e2f77539e16f8a6a7414/src/events/picker.js#L33) @bpatram. My secondary monitor is on top of the main one.

**Comment by Toinane** [comment]
Okey thanks for your precisions! I will test it on my mac tomorrow and try to resolve this problem asap!
It's a cool plugin @romanrandom :D

**Comment by bpatram** [comment]
Thank you @romanrandom! @Toinane I was able to pull down `master` and throw a breakpoint in and I can confirm the `x` position is reporting a negative value when my cursor is on my second display. It seems the position origin is reported as being the top left corner of the primary monitor (which is different than what xdotool reports, which is interesting).

**Comment by Toinane** [comment]
Okey I was able to reproduce the bug on my mac, I don't see the bug on Windows.

**Comment by Toinane** [comment]
Okey it's now good! You can download the fixe here: https://github.com/Toinane/colorpicker/releases/tag/2.0.1 :)

I will add a auto updated in future, It will be much easier.

Thank you @bpatram & @romanrandom for your help!

**Comment by bpatram** [comment]
Confirming that the latest version (2.0.1) resolves the issue! Thank you everyone! :)

**Comment by Louis-7** [comment]
Thank you! It's working on my environment.
