### ISSUE TITLE
Font awesome toggle icons not displaying in the settings window

### ISSUE THREAD

**Issue by andrei-agulescu** [Toinane/colorpicker#28]
I have noticed that the font awesome toggle icons used in the settings pane are not displaying (a box is displayed instead of the actual font awesome icon).

I have identified the issue to be the font-family css attribute value in views/css/settings.css (lines 128 and 131): 'FontAwesome' is the incorrect font-family name.

The fix is simple: remove the font-family name from the css rules in the settings.css because the .fa class specifies the correct font-family name.

![colorpicker_fa_icon_issue](https://user-images.githubusercontent.com/13255768/43076129-dd4fd5c6-8e8b-11e8-8207-e4cbe5129b7a.PNG)

**Comment by Toinane** [comment]
Seem because I have installed Font-awesome locally and it's worked in my computers. But thank you for your issue & PR!
