### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by Elias-Graf** [Toinane/colorpicker#41]
Today I wanted to launch the colorpicker and was greeted by this error:

`Uncaught Exception:
TypeError: Error processing argument at index 1, conversion failure from Error: Invalid data: 
    at Object.showErrorBox (/Applications/Colorpicker.app/Contents/Resources/electron.asar/browser/api/dialog.js:283:20)
    at electronStorage.get (/Applications/Colorpicker.app/Contents/Resources/app.asar/src/storage.js:33:16)
    at /Applications/Colorpicker.app/Contents/Resources/app.asar/node_modules/async/dist/async.js:473:16
    at next (/Applications/Colorpicker.app/Contents/Resources/app.asar/node_modules/async/dist/async.js:5315:29)
    at /Applications/Colorpicker.app/Contents/Resources/app.asar/node_modules/async/dist/async.js:958:16
    at /Applications/Colorpicker.app/Contents/Resources/app.asar/node_modules/electron-json-storage/lib/storage.js:150:16
    at nextTask (/Applications/Colorpicker.app/Contents/Resources/app.asar/node_modules/async/dist/async.js:5310:14)
    at next (/Applications/Colorpicker.app/Contents/Resources/app.asar/node_modules/async/dist/async.js:5317:9)
    at /Applications/Colorpicker.app/Contents/Resources/app.asar/node_modules/async/dist/async.js:958:16
    at /Applications/Colorpicker.app/Contents/Resources/app.asar/node_modules/electron-json-storage/lib/storage.js:135:18`

I tried downloading a fresh version but that didn't change anything. 

In hope the issue is not to bad and it's not an error on my side

Elias :)

**Comment by Toinane** [comment]
Hey @Elias-Graf! Thanks for your issues.
I'm sorry to say it's an error from your side. The storage file is corrupted, you have to delete it..

To found the file *colorpicker.json*, you have to go :
- Mac OS: ~/Library/Application Support/colorpicker/storage/
- Windows: C:\Users\<you>\AppData\Local\colorpicker\storage\
- Linux: ~/.config/colorpicker/storage

Delete it and relaunch the app, it will work again 😄

**Comment by Toinane** [comment]
I will add a solution to delete this corrupted file directly from the app in future update

**Comment by Elias-Graf** [comment]
May I ask how the file got corrupted? Or why?

**Comment by Elias-Graf** [comment]
Mhh... I'm sorry to say but the path '/Library/Application Support/colorpicker/storage/' Does not seem to exist on my system.

**Comment by Toinane** [comment]
don't miss ~ before /Library -> ~/Library/... 👍 
Before delete this file, can you copy the content here? It will be allow me to understand why this file being corrupted

**Comment by Elias-Graf** [comment]
Oh, gee... I forgot I'm on mac I'm so sorry... used to windows... well the file is empty as far as I'm concerned.

**Comment by Elias-Graf** [comment]
Hm yeah.. renamed it, started the picker and it generated a new file... sorry to bother people like me shouldn't call themselves programer ':D

**Comment by Toinane** [comment]
> Oh, gee... I forgot I'm on mac I'm so sorry... used to windows... well the file is empty as far as I'm concerned.

Oh okey, really strange.. I suppose Colorpicker don't like an empty file. I will prevent this type of bug in future 😄

**Comment by Toinane** [comment]
Ahah no worries! This bug shouldn't happen anyway.

**Comment by s73b4n** [comment]
Just to indicate the correct path to windows users: 
C:\Users<you>\AppData\Roaming\Colorpicker\storage
And delete colorpicker.json

**Comment by Toinane** [comment]
> Just to indicate the correct path to windows users:
> 
> > C:\Users\AppData\Roaming\Colorpicker\storage
> 
> And delete colorpicker.json

Thank you! I've updated my post with the good path 👍
