### ISSUE TITLE
Windows fresh build fails

### ISSUE THREAD

**Issue by rodrigorhas** [Toinane/colorpicker#44]
As the title says, for about the last 3 hours (yup, this time) i was trying to do a simple `npm install` and i cannot get it to work due to:

- MSBuild Cpp errors (file is missing, may be a bug from executable)
- Python is required (v2.7 but not up to v3) to build robotjs
- and other weird issues related to the items above

I can't put the error messages here because i already solved some of them and i lost the error messages...

So, i thing all the issues i've got was related only to robotjs build.
Is there a way to skip this build process or even make it easier?

### UPDATE 1
i've just found some errors reported by the `npm install`

- MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0"
    - then i tried to `npm install --global --production windows-build-tools`  described here (https://github.com/chjj/pty.js/issues/60)
- C:\wamp64\www\colorpicker\node_modules\robotjs\build\robotjs.vcxproj(20,3): error MSB4019: The imported project "C:\Mic
rosoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the fil
e exists on disk.
- gyp ERR! stack import sys; print "%s.%s.%s" % sys.version_info[:3]; gyp ERR! stack ^ gyp ERR! stack SyntaxError: invalid syntax
    - this throws when i try to use python 3+ version

**Comment by Toinane** [comment]
Hey! Thanks for your PR!
yeah I'll need to make a documentation on how to compile colorpicker on local..

The delicate part is related to native module like robotjs, win-mouse and osx-mouse.
For windows, you have to : 
- install windows-build-tools npm package (`npm install --global --production windows-build-tools` from an elevated PowerShell or CMD.exe)
- install node-gyp `npm install -g node-gyp`

when you run `npm install`, it should just install all dependencies, you'll need to run `npm run rebuild`, this command will rebuild all native modules for the version of Electron Colorpicker use.

**Comment by rodrigorhas** [comment]
Damn. This is so annoying. I'll give it a try later and I'll report back if your "recipe" is right haha :grinning:

**Comment by Toinane** [comment]
Yeah sorry 😞It's not so easy to add native module into Electron project.. And I need it to make picker work.

**Comment by Toinane** [comment]
For this issue, I'll update the readme with more informations. Since I'll change the picker feature in next update, this will be more easier to build for development 👍
