### ISSUE TITLE
App does not start at all - Error processing argument at index 1

### ISSUE THREAD

**Issue by jsgoupil** [Toinane/colorpicker#57]
When trying to start the app, I get an error. I also have uninstalled it and re-installed it.
I have 2 monitors, they have different DPI. I remember the app was not liking that much when it came to use the pipet.

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Error processing argument at index 1, conversion failure from Error: Invalid data: 
    at Object.showErrorBox (C:\Users\asus\AppData\Local\Programs\Colorpicker\resources\electron.asar\browser\api\dialog.js:283:20)
    at electronStorage.get (C:\Users\asus\AppData\Local\Programs\Colorpicker\resources\app.asar\src\storage.js:33:16)
    at C:\Users\asus\AppData\Local\Programs\Colorpicker\resources\app.asar\node_modules\async\dist\async.js:473:16
    at next (C:\Users\asus\AppData\Local\Programs\Colorpicker\resources\app.asar\node_modules\async\dist\async.js:5315:29)
    at C:\Users\asus\AppData\Local\Programs\Colorpicker\resources\app.asar\node_modules\async\dist\async.js:958:16
    at C:\Users\asus\AppData\Local\Programs\Colorpicker\resources\app.asar\node_modules\electron-json-storage\lib\storage.js:150:16
    at nextTask (C:\Users\asus\AppData\Local\Programs\Colorpicker\resources\app.asar\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\asus\AppData\Local\Programs\Colorpicker\resources\app.asar\node_modules\async\dist\async.js:5317:9)
    at C:\Users\asus\AppData\Local\Programs\Colorpicker\resources\app.asar\node_modules\async\dist\async.js:958:16
    at C:\Users\asus\AppData\Local\Programs\Colorpicker\resources\app.asar\node_modules\electron-json-storage\lib\storage.js:135:18

[OK]
```

**Comment by jsgoupil** [comment]
I did some digging, the file here:
"C:\Users\asus\AppData\Roaming\Colorpicker\storage\colorpicker.json"
was fully empty.
I deleted the storage folder and it started to work again.

You might have 2 problems to fix with this bug.

1. You apparently can't pass "err" to the dialog
2. Fallback better when this problem happens on startup, otherwise I am stuck forever and could not start the software.

**Comment by Toinane** [comment]
Hey ! Sorry for the late response, yeah I know this issue, it was fixed for the next big update, I just don't have so much time for the moment to continue this update but it will be cool to fix this as soon as possible!

**Comment by Toinane** [comment]
should now fixed in https://github.com/Toinane/colorpicker/releases/tag/2.2.1
Feel free to reopen if needed!
