### ISSUE TITLE
Appimage don't run

### ISSUE THREAD

**Issue by n1c0saurio** [Toinane/colorpicker#58]
The app crash instantly, returning this message in the console: 
``` bash
(colorpicker:6038): Pango-ERROR **: 22:53:38.990: Harfbuzz version too old (1.4.2)
```
Perhaps is related to [an outdated Electron version used in this app](https://github.com/electron/electron/issues/20348).

OS: Fedora Workstation 31, 64 bits
App ver.: 2.0.0

**Comment by Toinane** [comment]
Hey, thanks for the reporting! I will check this asap and make a new build!

**Comment by Toinane** [comment]
@n1c0saurio Okay, a lot of complications here ahah!
The dependencies were all incompatible with the latest versions of Electron and Node, I had to update them myself and I haven't updated the one for windows yet.
For the moment all work now with the latest version on MacOS. When I can, I'll test that on Windows & Linux (I have Debian & ElementaryOS)
See #59

**Comment by Toinane** [comment]
Hey @n1c0saurio I've just released a new version that should be resolve your problem! See https://github.com/Toinane/colorpicker/releases/tag/2.0.3
Feel free to reopen this issues if needed 👍
