### ISSUE TITLE
The interface gets confusing with the opacity feature

### ISSUE THREAD

**Issue by Toinane** [Toinane/colorpicker#68]
> Dragging the shade bar breakes the interface, see screenshot below.
> ![image](https://user-images.githubusercontent.com/57003922/77566297-31f43000-6ea4-11ea-9cc1-7c2d01905c13.png)

Bug emitted by @cristianovitorino

**Comment by Toinane** [comment]
I know this bug is from newest version of Electron, before 4.0.0 this bug doesn't exist. I'll search if newest version of Electron resolve this or if I need to change something in my code.

**Comment by Xenoglyphic** [comment]
On Ubuntu 18.04 this bug only seems to exist in the snap version.  I installed the deb file and now it works like a charm.
I need to do more testing to know there aren't any bugs for sure.

**Comment by Toinane** [comment]
Thanks for your reporting 😄

**Comment by Xenoglyphic** [comment]
I don't know why but the deb versions opacity setting is now broken, no updates or anything...

I'll have to look into it a little more...

**Comment by Toinane** [comment]
> I don't know why but the deb versions opacity setting is now broken, no updates or anything... 
> I'll have to look into it a little more...

Yeah this feature is broken for every platform.. I need to see if Electron support this well or if I need to delete this buggy feature for now

> isn't the hex number supposed to have the opacity included in it when this feature is enabled?
Not for the moment, but it could be useful yeah

**Comment by Xenoglyphic** [comment]
Ok, thank you for clarifying!
I hope we can work this out...

**Comment by Toinane** [comment]
Look be ok on the new update now!
