### ISSUE TITLE
Color Pick not working on snap

### ISSUE THREAD

**Issue by EndrII** [Toinane/colorpicker#72]
ubuntu 19.10 
stable chanel of snap store 

![image](https://user-images.githubusercontent.com/12465465/78498898-11ef2700-7756-11ea-8331-012d062b1dfd.png)

![image](https://user-images.githubusercontent.com/12465465/78498950-5d093a00-7756-11ea-9935-4aaf83fe1200.png)

**Comment by Toinane** [comment]
Hey thanks for the reporting!
Yeah I know I don't really understand why it's not working, my building file include the needed library. For the moment in classic confinement, it's work but it's not the best solution. I'll test others possibilities to workaround this.. Sorry for the inconvenient!

**Comment by EndrII** [comment]
where is your snapcraft.yaml?

**Comment by Toinane** [comment]
Sorry for the late response, you can find the file here: #73

**Comment by Toinane** [comment]
before using the snapcraft yaml, I've used electron-builder to build snap file but I suppose electron-builder doesn't want to build my dependency

**Comment by Xenoglyphic** [comment]
On Ubuntu 18.04 the snap has a ton of issues. I installed the deb file which, for some reason, works well, so far I haven't found any severe issues to report.

**Comment by Toinane** [comment]
Yeah.. I don't really know why.. maybe  Electron-builder isn't the best option to build for snapcraft

**Comment by Toinane** [comment]
Okay! I've resolved the problem! I've publised a new beta release on the snapcraft store here: https://snapcraft.io/colorpicker-app
Can you confirm it's now work for you @EndrII @Xenoglyphic ? After that I publish it on stable channel!

**Comment by Toinane** [comment]
It's work for me on Ubuntu 19.10 with gnome

**Comment by Xenoglyphic** [comment]
It works for me!
I forgot to ask this earlier, but, why is it's movement so laggy?
the deb package has the same issue.

**Comment by Toinane** [comment]
great! 
I don't really know why, I don't have this issue with my Linux. But I suppose it's because I use a native package which is not very well supported by Electron and Linux. At the moment it's my only way to get the picker to work on Linux. I will rewrite all the code of the application soon with the goal to make the application as performant as possible. I hope that it will be better at this time!

**Comment by Xenoglyphic** [comment]
Cool, I have an idea why.
I just rebooted my computer, which sadly didn't fix the opacity setting, and the picker worked a ton better than before, but after I launched all my programs and browsers that I usually have open the picker started stuttering again.
have you made the picker able to use multiple cores from the cpu, or does it draw on another resource?

**Comment by Toinane** [comment]
Hmm okay, I'm not surprised about the opacity, it's very unstable. For the picker, it may be related to that indeed, I'll have to investigate on the subject. I also noticed that it was also slower when you're on a 2nd screen.

**Comment by Toinane** [comment]
I've opened a new issue about the picker, we should now use this issue #74 😃 The picker now work on snap so I'll close it!

**Comment by Xenoglyphic** [comment]
sweet!
