### ISSUE TITLE
Display Scale other than 100%: The color picker circle widget's position doesn't match the cursor [Windows 10]

### ISSUE THREAD

**Issue by LarsJandel** [Toinane/colorpicker#76]
**Describe the bug**
The color picker widget doesn't adapt to other Windows UI scaling than 100% → it does sample the color under the mouse, but the widget ring gets more and more offset when moving away from the 0, 0 upper left corner coordinate of the screen.

**To Reproduce**
1. Windows 10 / Settings / Display
2. Set Scale to a higher number than 100%
3. Activate the color picker

**Expected behavior**
The color picker circle widget position should match the cursor.

**Screenshots**
![DisplayScaleIssue](https://user-images.githubusercontent.com/32457827/81044405-8e3f6c00-8eb4-11ea-90f2-d5ec4ccb58c0.png)
.

**OS (please complete the following information):**
 - Windows 10 Home
 - 1909

**Colorpicker (please complete the following information):**
 - 2.0.3

**Comment by Toinane** [comment]
Hey @LarsJandel thank's for reporting this bug!
I can reproduce it on my Windows 10. It will be resolved in the next big update, I'll use a new picker desgin (see #74) :+1:

**Comment by LarsJandel** [comment]
Cool - thanks!

**Comment by jamespotz** [comment]
This also happens on Linux 
![Screenshot from 2020-06-05 23-09-44](https://user-images.githubusercontent.com/4239625/83892749-ac351080-a781-11ea-8810-f31b6330ee98.png)

**Comment by Toinane** [comment]
Good to know! Thank you 😀

**Comment by jamespotz** [comment]
@Toinane this might help, I've tested it without a dual monitor and its working fine, It only occurs on dual monitor setup
![Screenshot from 2020-06-06 08-28-33](https://user-images.githubusercontent.com/4239625/83931551-e7f6c700-a7cf-11ea-91f1-1fdc49482a6d.png)

**Comment by Toinane** [comment]
Oh okey interesting.. Ill test on Windows too maybe its similar. Thank you for the precision ! 👍

**Comment by Toinane** [comment]
It's now fixed in 2.2.0 👍
