### ISSUE TITLE
Icon tool bar too dark

### ISSUE THREAD

**Issue by m21-cerutti** [Toinane/colorpicker#84]
![image](https://user-images.githubusercontent.com/23432929/88575846-cafaa980-d044-11ea-805f-474d76494ce4.png)

 I can't see Icon on black minimize.

**Comment by Toinane** [comment]
Hey @m21-cerutti thank you for your issue, but it's a duplicate of #48 👍

**Comment by m21-cerutti** [comment]
Ok sorry for that ^^.

**Comment by Toinane** [comment]
no worries 😄
