### ISSUE TITLE
Color circle offset on 4k screens

### ISSUE THREAD

**Issue by bcanteneurEiffage** [Toinane/colorpicker#94]
**Describe the bug**
I work on a 4k screen (4K UHD 3840 x 2160 pixels) and when I start the picker, the circle supposed to be around the pointer is offset. See the image for beter understanding.

**To Reproduce**
1. Start Application
2. Click on 'Pick Color'

**Expected behavior**
Color circle should be around the mouse pointer

**Screenshots**
![image](https://user-images.githubusercontent.com/68943107/105512154-0ebb2c80-5cd1-11eb-83f1-5bc6cf40aa88.png)

**OS (please complete the following information):**
 - OS: Windows 10 Family
 - Version 10.0.19042

**Colorpicker (please complete the following information):**
 - Version 2.0.3

**Additional context**
No additional contect

**Comment by Toinane** [comment]
Hey @bcanteneurEiffage thank you for your issue! It's a know issue like here #76
Can you confirm your windows scale is other than 100%?

**Comment by bcanteneurEiffage** [comment]
@Toinane Hi! yes it is 250%. Issue should come from here.

Sorry for the french screenshot :
![image](https://user-images.githubusercontent.com/68943107/106474852-9d843200-64a5-11eb-934e-f590206f2cf6.png)

**Comment by Toinane** [comment]
Oui je confirme le soucis vient de ça :) je suis aussi français !

**Comment by bcanteneurEiffage** [comment]
Ok parfait si c'est connu alors :) Au moins, contrairement à d'autres colorpicker, il prend la bonne couleur et on picker une couleur sur tout l'écran même si le cercle n'est pas bien calé.

**Comment by Toinane** [comment]
Hello @bcanteneurEiffage C'est maintenant fixé dans la v2.2.0! Désolé pour la lenteur du fix!
