### ISSUE TITLE
App Crashed and can't replicated

### ISSUE THREAD

**Issue by darkRaspberry** [Toinane/colorpicker#97]
**Describe the bug**
app CRASHED, Please Refer to screenshot

**To Reproduce**
I was testing ramdom colors and got a dark color.
Then I was toggling shadding and the app crashed. I forget to note the colour, The app crashed at that color many times. But can't replicated it next time.

**Expected behavior**
DOESN'T CRASH

**Screenshots**
![Screenshot from 2021-03-07 22-01-12](https://user-images.githubusercontent.com/56693429/110247311-a5962c80-7f91-11eb-90d2-7021f6cf3a0f.png)

**OS (please complete the following information):**
 - OS: Ubuntu 20.10 
 - Kernel: 5.8.0-44-generic

**Colorpicker (please complete the following information):**
 - Version 2.0.3

**Additional context**

**Comment by Toinane** [comment]
Hey @darkRaspberry thank you for your report, its strange crash yeah! I suppose its a bug with Electron directly, so for the moment I can't really do something but the next update will use the latest Electron version. I hope this will be fixed with that

**Comment by Toinane** [comment]
Should be fixed in 2.1.0 now!
